###
GET http://localhost:8080/airline

###
GET http://locarhost:8080/airline/1

###
POST http://localhost:8080/airline
Connect-type: application/json
{
    "Name": "test"
}
###
DELETE http://localhost:8080/airport/1

###
PUT http://localhost:8080/airline/1
Content-Type: application/json

{
    "name": "test_1"
}
