## Author: Maciej Deroń

### Get flight by id
GET http://localhost:8080/flight/1
Accept: application/json

### Get all flights
GET http://localhost:8080/flight
Accept: application/json

### Get flights with parameters
GET http://localhost:8080/flight?departureAirport=test1&arrivalAirport=test2&departureTime=2024-01-20T09:00:00&arrivalTime=2024-01-20T15:00:00
Accept: application/json

### Create a new flight
POST http://localhost:8080/flight
Content-Type: application/json
Accept: application/json

{
  "flightNumber": "AV-1233",
  "departureAirport": "test1",
  "arrivalAirport": "test2",
  "departureTime": "2024-01-20T10:00:00",
  "arrivalTime": "2024-01-20T14:00:00",
  "planeId": 1,
  "airline": "test",
  "price": 500.00
}

### Update departure time of a flight
PUT http://localhost:8080/flight/1/departure-time
Content-Type: application/json
Accept: application/json

{
  "departureTime": "2024-01-20T11:00:00"
}

### Update price of a flight
PUT http://localhost:8080/flight/1/price
Content-Type: application/json
Accept: application/json

{
  "price": 600.00
}

### Delete a flight
DELETE http://localhost:8080/flight/1
Accept: application/json