###
GET http://localhost:8080/passenger

###
GET http://localhost:8080/passenger/1

###
POST http://localhost:8080/passenger
Content-Type: application/json

{
  "firstName": "test2",
  "lastName": "test",
  "email": "test@email.com",
  "phoneNumber": "123456789",
  "dateOfBirth": "1990-01-01"
}

###
DELETE http://localhost:8080/passenger/1

###
PUT http://localhost:8080/passenger/1
Content-Type: application/json

{
    "email": "email@test.com"
}
