## Author: Maciej Deroń

###
GET http://localhost:8080/plane

###
GET http://localhost:8080/plane/1

###
POST http://localhost:8080/plane
Content-Type: application/json

{
  "model": "test",
  "airline": "test",
  "numberOfSeats": 100
}

###
DELETE http://localhost:8080/plane/1