## Authors: Mariusz Ignaciuk, Paweł Dostal, Julia Dziekańska

###
GET http://localhost:8080/ticket

###
GET http://localhost:8080/ticket/1

###
GET http://localhost:8080/ticket/user/1?active=true

###
DELETE http://localhost:8080/ticket/1

###
POST http://localhost:8080/ticket
Content-Type: application/json

{
  "flightId": 1,
  "email": "email@test.com"
}